export const ADD_INGREDIENT ="ADD_INGREDIENT";
export const REMOVE_INGREDIENT ="REMOVE_INGREDIENT";
export const INIT_INGREDIENT_SUCCES="INIT_INGREDIENT_SUCCES"


export const START_SENDING_ORDER ="START_SENDING_ORDER"
export const SUCCES_SENDING_ORDER="SUCCES_SENDING_ORDER"
export const FAIL_SENDING_ORDER  ="FAIL_SENDING_ORDER"